### PR TITLE
Add thewchan as maintainer

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thewchan** [comment]
@conda-forge-admin, please rerender

**Comment by thewchan** [comment]
@oblute @Tata17 Several packages waiting for a newer version of this; if possible please add me to help maintain this package.

**Comment by thewchan** [comment]
@conda-forge/core 

Seems like both maintainer were both inactive since Feb (see PRs), is it possible to skip the wait let add me as a maintainer?

**Comment by oblute** [comment]
Planning on getting to this in the next week, been a bit of a backlog. Happy to add you as a maintainer but we will be fixing this soon.

**Comment by thewchan** [comment]
@oblute Thanks! Sorry didn't mean to rush

**Comment by oblute** [comment]
Getting on the update now :) No worries.

**Comment by thewchan** [comment]
@oblute Ok this is ready to go!

**Pull request merged**
